[mesh]
file = "(in-memory)"

[frequency]
values = [1000000000, 5000000000, 1e+10, 3e+10, 6e+10, 1e+11]

[[ports]]
type = "abc"
tag = 10
order = 1
abctype = "B"

[[ports]]
type = "lumped"
tag = 7
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[ports]]
type = "lumped"
tag = 9
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[materials]]
volume_tag = 13
er = 1
ur = 1
tand = 0
conductivity = 0

[[materials]]
volume_tag = 11
er = 11.9
ur = 1
tand = 0
conductivity = 10

[[materials]]
volume_tag = 12
er = 4.2
ur = 1
tand = 0
conductivity = 0

[pec]
tags = [4, 3, 5, 6, 8]

[output]
z0 = 50
