[mesh]
file = "(in-memory)"

[frequency]
values = [1000000000, 3000000000, 5000000000]

[[ports]]
type = "abc"
tag = 9
order = 1
abctype = "B"

[[ports]]
type = "lumped"
tag = 6
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[ports]]
type = "lumped"
tag = 8
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[materials]]
volume_tag = 12
er = 1
ur = 1
tand = 0
conductivity = 0

[[materials]]
volume_tag = 10
er = 11.9
ur = 1
tand = 0
conductivity = 10

[[materials]]
volume_tag = 11
er = 4.2
ur = 1
tand = 0
conductivity = 0

[pec]
tags = [4, 3, 5, 7]

[output]
z0 = 50
