[mesh]
file = "(in-memory)"

[frequency]
values = [1000000000, 1e+10, 3e+10, 5e+10, 8e+10, 1.1e+11, 1.4e+11, 1.7e+11, 2e+11, 2.3e+11, 2.5e+11]

[[ports]]
type = "lumped"
tag = 5
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[ports]]
type = "lumped"
tag = 7
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[ports]]
type = "abc"
tag = 8
order = 1
abctype = "B"

[[materials]]
volume_tag = 11
er = 1
ur = 1
tand = 0
conductivity = 0

[[materials]]
volume_tag = 9
er = 11.9
ur = 1
tand = 0
conductivity = 10

[[materials]]
volume_tag = 10
er = 4.2
ur = 1
tand = 0
conductivity = 0

[pec]
tags = [1, 4, 6]

[output]
z0 = 50
