[mesh]
file = "(in-memory)"

[frequency]
values = [1000000000, 2000000000, 3000000000, 4000000000, 5000000000]

[[ports]]
type = "lumped"
tag = 5
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[ports]]
type = "lumped"
tag = 6
z0 = 50
power = 1
direction = [0, 0, 1]
width = 0
height = 0

[[ports]]
type = "abc"
tag = 7
order = 1
abctype = "B"

[[materials]]
volume_tag = 10
er = 1
ur = 1
tand = 0
conductivity = 0

[[materials]]
volume_tag = 8
er = 11.9
ur = 1
tand = 0
conductivity = 10

[[materials]]
volume_tag = 9
er = 4.2
ur = 1
tand = 0
conductivity = 0

[pec]
tags = [1, 4]

[output]
z0 = 50
