//! Exact port of touchstone.py: Touchstone S-parameter file export.

use num_complex::Complex64 as C64;
use std::io::Write;

/// Write S-parameters to a Touchstone file.
/// Port of touchstone.py:generate_touchstone().
///
/// `frequencies`: frequency points in Hz
/// `s_params`: s_params[freq_idx][row][col] — complex S-matrix per frequency
/// `n_ports`: number of ports
/// `z0`: reference impedance (default 50Ω)
pub fn write_touchstone(
    path: &str,
    frequencies: &[f64],
    s_params: &[Vec<Vec<C64>>],
    n_ports: usize,
    z0: f64,
) -> std::io::Result<()> {
    let mut file = std::fs::File::create(path)?;

    // Header
    writeln!(file, "! Touchstone file generated by RapidFEM")?;
    writeln!(file, "! Ports: {}", n_ports)?;
    writeln!(file, "# GHZ S RI R {:.0}", z0)?;

    // Data: one line per frequency
    for (fi, &freq) in frequencies.iter().enumerate() {
        let freq_ghz = freq / 1e9;
        write!(file, "{:.6e}", freq_ghz)?;

        // S-parameter ordering: row-major for S2P
        // S2P format: freq S11_re S11_im S21_re S21_im S12_re S12_im S22_re S22_im
        if n_ports <= 2 {
            for i in 0..n_ports {
                for j in 0..n_ports {
                    let s = s_params[fi][i][j];
                    write!(file, " {:.8e} {:.8e}", s.re, s.im)?;
                }
            }
            writeln!(file)?;
        } else {
            // SNP (N>2): 4 values per line after frequency, then continuation lines
            let mut vals = Vec::new();
            for i in 0..n_ports {
                for j in 0..n_ports {
                    let s = s_params[fi][i][j];
                    vals.push(s.re);
                    vals.push(s.im);
                }
            }
            for (vi, &v) in vals.iter().enumerate() {
                if vi > 0 && vi % 8 == 0 {
                    writeln!(file)?;
                    write!(file, "           ")?;
                }
                write!(file, " {:.8e}", v)?;
            }
            writeln!(file)?;
        }
    }

    Ok(())
}
