/** Demo example registry. msh + toml are pre-built by wasm-demo/scripts/. */

export type Metric =
	| 'L_eq'    // π-equivalent series inductance — meaningful for inductors
	| 'Q'       // quality factor at port 1 — meaningful for inductors / resonators
	| 'Z0';     // characteristic impedance — meaningful for transmission lines

export interface DemoExample {
	id: string;
	label: string;
	description: string;
	msh_url: string;
	toml_url: string;
	frequencies_hz: number[];
	/** Lumped/TL metrics to extract from the S-matrix and display. */
	metrics: Metric[];
}

export const EXAMPLES: Record<string, DemoExample> = {
	wr90: {
		id: 'wr90',
		label: 'WR-90 waveguide',
		description: 'Rectangular hollow waveguide, dominant TE10 mode, fundamental EM benchmark.',
		msh_url: '/examples/wr90_straight.msh',
		toml_url: '/examples/wr90.toml',
		frequencies_hz: [9e9, 9.25e9, 9.5e9, 9.75e9, 10e9, 10.25e9, 10.5e9, 10.75e9, 11e9],
		metrics: []
	},
	microstrip: {
		id: 'microstrip',
		label: 'Sky130 microstrip',
		description: '200 µm × 5 µm trace on met5 over a continuous li1 ground strip — true microstrip topology. Best characterised by Z0 and the loss tangent, not lumped L/Q.',
		msh_url: '/examples/microstrip.msh',
		toml_url: '/examples/microstrip.toml',
		frequencies_hz: [1e9, 2e9, 3e9, 4e9, 5e9],
		metrics: ['Z0']
	},
	spiral: {
		id: 'spiral',
		label: 'Sky130 spiral inductor',
		description: 'Octagonal 1-turn 80 µm spiral on met5 with local li1 ground patches. Sweep captures L_eq(f) and the self-resonance.',
		msh_url: '/examples/spiral.msh',
		toml_url: '/examples/spiral.toml',
		frequencies_hz: [1e9, 10e9, 30e9, 50e9, 80e9, 110e9, 140e9, 170e9, 200e9, 230e9, 250e9],
		metrics: ['L_eq', 'Q']
	},
	rp_spiral: {
		id: 'rp_spiral',
		label: 'rapidpassives · spiral',
		description: 'Layout generated by rapidpassives.SpiralInductor (Dout=80µm, N=1, sides=8) → bridged into rapidfem mesh. Demonstrates the rapidpassives → rapidfem pipeline.',
		msh_url: '/examples/rp_spiral.msh',
		toml_url: '/examples/rp_spiral.toml',
		frequencies_hz: [1e9, 5e9, 10e9, 30e9, 60e9, 100e9],
		metrics: ['L_eq', 'Q']
	},
	rp_symmetric: {
		id: 'rp_symmetric',
		label: 'rapidpassives · symmetric inductor',
		description: 'Layout from rapidpassives.SymmetricInductor (Dout=100µm, N=2). Center-tap symmetric spiral, simulated as a 2-port differential structure.',
		msh_url: '/examples/rp_symmetric.msh',
		toml_url: '/examples/rp_symmetric.toml',
		frequencies_hz: [1e9, 5e9, 10e9, 30e9, 60e9, 100e9],
		metrics: ['L_eq', 'Q']
	}
};
