"""Octagonal spiral inductor on Sky130 — 2-layer stack with merged via.

A symmetric 2-turn octagonal spiral, generated by
``rapidpassives.SpiralInductor`` (the open-source DRC-clean RFIC layout
generator). Three conductor pieces live on the Sky130 stack:

- **Winding** on met5 (top metal) — closed polygon with built-in port
  tabs at the outer edge.
- **Crossing** on met4 — short rectangle that routes the spiral's
  inner endpoint back out under the windings.
- **Via** on via4 — a single merged conductor block (from the
  ``via_merge=True`` mode of the generator).

Every metal piece is extruded to its real PDK thickness (met5 = 1.26 µm,
met4 = 0.845 µm, via4 between met4 top and met5 bottom). This keeps the
geometry honest at >10 GHz where the skin depth in aluminium drops
below the metal thickness and a thin-conductor approximation would
under-represent eddy-current losses + edge field crowding.

The two lumped-port plates sit one tab-half INSIDE the conductor's
outer edge so their top edge lands on the conductor's BOTTOM face
(horizontal, normal ẑ — PEC there constrains only E_x and E_y, leaving
E_z free for the port drive). Flush with the outer edge the top edge
would land on the vertical SIDE WALL, where PEC sets E_z = 0 and
fights the port BC, producing an open-circuit S-matrix.

Both lumped ports sit at the outer edge — Port 1 at the winding's
start tab (y > 0), Port 2 at the crossing's outboard end (y < 0).
They share ONE local ground patch on li1 directly under both port
plates. That matches a real GSG-probe measurement (both probe grounds
tie to the station chassis at the same potential) and gives a
well-defined common reference for the 2-port S matrix — try splitting
it into two disjoint patches and the extraction blows up because the
two ports no longer share a return path.

Series inductance from the 2-port Z matrix:

    L_series = Im(Z11 - Z21) / ω

(extracting via 1/(ω·Im(Y21)) instead is a classic trap — Im(Y21) ends
up as the tiny remainder of two near-equal shunt admittances and
divides into nonsense.)

Compared against the Mohan modified-Wheeler formula (octagonal:
K1=2.25, K2=3.55). At the demo mesh size the FEM lands inside the
factor-of-2 corridor Mohan itself is quoted within (Mohan has ~5-10%
error vs measurement, then the FEM picks up port-plate parasitic loop
inductance + finite-metal-thickness effects). Refine MAXH and
SPIRAL_MAXH for tighter agreement.
"""

# %% Parameters
import math
import numpy as np
import rapidfem as rf
import rapidfem.rfic as rfic

# Layout generator — vendored from milanofthe/rapidpassives, MIT licensed.
# Kept as an import (not a hard dep) so the rapidfem wheel stays slim; pip
# install rapidpassives to run this example locally.
from rapidpassives.spiralinductor import SpiralInductor

um = 1e-6
MU0 = 4 * math.pi * 1e-7

DOUT_UM    = 90.0        # outer diameter of the spiral
N_TURNS    = 2
SIDES      = 8           # octagon
WIDTH_UM   = 8.0
SPACING_UM = 4.0
FREQS_HZ   = np.linspace(1e9, 60e9, 25)           # 1 → 60 GHz across the band

# Sky130 process stack — gives realistic z-stack-up and per-layer materials.
stack = rfic.Stack.sky130()
PDK_WIND  = stack.by_name("met5")   # winding
PDK_CROSS = stack.by_name("met4")   # crossing under the winding
PDK_VIA   = stack.by_name("via4")   # via between met4 and met5
PDK_GND   = stack.by_name("li1")    # ground reference

Z_WIND      = PDK_WIND.z                            # met5 bottom
Z_WIND_TOP  = PDK_WIND.z + PDK_WIND.thickness       # met5 top
Z_CROSS     = PDK_CROSS.z                           # met4 bottom
Z_CROSS_TOP = PDK_CROSS.z + PDK_CROSS.thickness     # met4 top
Z_VIA_LO    = Z_CROSS_TOP                           # via4 bottom (met4 top)
Z_VIA_HI    = Z_WIND                                # via4 top (met5 bottom)
Z_GND       = PDK_GND.z + PDK_GND.thickness         # top of li1

FOOT       = 1.6 * DOUT_UM * um               # in-plane footprint
AIR_H      = 60 * um
MAXH       = 18 * um                          # global mesh cap (substrate / air)
METAL_MAXH = 1.5 * um                         # refinement on the conductor
                                              # volumes — comparable to met5's
                                              # 1.26 µm thickness so the bottom
                                              # and top caps get 2-3 cells across
PORT_MAXH  = 1.5 * um                         # refinement on the port plates
                                              # + shared ground patch


# %% Generate the spiral layout
ind = SpiralInductor(Dout=DOUT_UM, N=N_TURNS, sides=SIDES,
                     width=WIDTH_UM, spacing=SPACING_UM,
                     via_width=2.0, via_spacing=1.0, via_in_metal=1.0,
                     via_merge=True)            # single merged via block

winding_xy_um  = list(zip(*ind.layers["windings"][0]))    # [(x, y), ...]
crossing_xy_um = list(zip(*ind.layers["crossings"][0]))
via_xy_um      = list(zip(*ind.layers["vias"][0]))         # 4-vertex rectangle

# Mohan modified-Wheeler reference (octagonal coefficients)
din_um = DOUT_UM - 2 * N_TURNS * (WIDTH_UM + SPACING_UM)
davg   = (DOUT_UM + din_um) / 2 * um
rho    = (DOUT_UM - din_um) / (DOUT_UM + din_um)
L_MOHAN = 2.25 * MU0 * N_TURNS ** 2 * davg / (1 + 3.55 * rho)


# %% Geometry: stack-up + 2-layer spiral + vias + ports
g = rf.Geometry(maxh=MAXH)

# Sky130 substrate + oxide (Stack assigns rf.Dielectric instances directly).
subs = stack.create_substrate(g, footprint=(FOOT, FOOT), center=True,
                              fragment_existing=False)
substrate, oxide = subs["substrate"], subs["oxide"]

air = g.box(FOOT, FOOT, AIR_H,
            position=(-FOOT / 2, -FOOT / 2, stack.top_z),
            material=rf.Air())

# Winding (met5) — closed polygon extruded UP to met5.thickness. PEC will
# bound the resulting 3-D conductor on every face. The maxh hint MUST go on
# the extruded VOLUME, not on the source polygon — the polygon face becomes
# the volume's bottom cap and may be sub-divided by fragment (the via box
# cuts a chunk out of it), which loses any attribute set on the original
# face. Per-volume maxh propagates to every boundary surface and survives.
winding_face = g.polygon(
    [(x * um, y * um, Z_WIND) for x, y in winding_xy_um])
winding = g.extrude(winding_face, height=PDK_WIND.thickness,
                    material=oxide.material, maxh=METAL_MAXH)

# Crossing (met4) — short rectangle, same treatment.
crossing_face = g.polygon(
    [(x * um, y * um, Z_CROSS) for x, y in crossing_xy_um])
crossing = g.extrude(crossing_face, height=PDK_CROSS.thickness,
                     material=oxide.material, maxh=METAL_MAXH)

# Merged via (via4) — 3-D conductor block at the physical via location
# (met4 top → met5 bottom). The volume tets need a permittivity for the FEM
# assembly even though PEC bounds the surface; oxide is fine since no field
# penetrates a PEC volume anyway.
via_x = [p[0] * um for p in via_xy_um]
via_y = [p[1] * um for p in via_xy_um]
via = g.box(max(via_x) - min(via_x),
            max(via_y) - min(via_y),
            Z_VIA_HI - Z_VIA_LO,
            position=(min(via_x), min(via_y), Z_VIA_LO),
            material=oxide.material,
            maxh=METAL_MAXH)

# Lumped-port plates + ONE shared local ground patch on li1 underneath both
# outer tabs. Port 1 drives between winding (met5) tab and the patch;
# Port 2 drives between crossing (met4) tab and the same patch.
PORT_X       = (DOUT_UM / 2 + WIDTH_UM / 2) * um        # tab CENTRE x (inside
                                                        # the conductor footprint
                                                        # so port-plate tops land
                                                        # on the BOTTOM face)
TAB_Y_OUTER  = (WIDTH_UM + SPACING_UM) / 2 * um         # centerline of upper tab
TAB_HALF     = WIDTH_UM / 2 * um                        # tab half-height in y
GND_W        = 3 * WIDTH_UM * um                        # patch width  (x)
GND_H        = 3 * (WIDTH_UM + SPACING_UM) * um         # patch height (y)

# Shared local ground patch spanning both port footprints in y.
gnd = g.xy_plate(GND_W, GND_H,
                 position=(PORT_X - GND_W / 2, -GND_H / 2, Z_GND),
                 maxh=PORT_MAXH)

# Port 1 — winding side (upper tab, y > 0). Drops to the shared gnd patch.
port1 = g.plate(
    p0=(PORT_X, TAB_Y_OUTER - TAB_HALF, Z_GND),
    width=(0, 2 * TAB_HALF, 0),
    height=(0, 0, Z_WIND - Z_GND),
    maxh=PORT_MAXH,
)

# Port 2 — crossing side (lower tab, y < 0). Drops only to met4 bottom.
port2 = g.plate(
    p0=(PORT_X, -TAB_Y_OUTER - TAB_HALF, Z_GND),
    width=(0, 2 * TAB_HALF, 0),
    height=(0, 0, Z_CROSS - Z_GND),
    maxh=PORT_MAXH,
)

# Conformal fragment: every metal volume + the port + air in ONE call. Air is
# in there because the extruded winding's TOP face sits at stack.top_z and
# touches the oxide-air interface — without fragmenting air the coincident
# faces at that interface stay non-conformal and field continuity above the
# winding breaks.
g.fragment(oxide, substrate, winding, crossing, via, gnd, port1, port2, air)

# BCs: every conductor surface is PEC, ports are lumped, outer air is ABC.
# 3-D volumes don't suffer the post-fragment splitting that thin 2-D plates
# do, so winding.faces / crossing.faces give the complete PEC surface.
rf.PEC(winding.faces, crossing.faces, via.faces, gnd)
rf.LumpedPort(port1, direction=(0, 0, 1), z0=50.0)
rf.LumpedPort(port2, direction=(0, 0, 1), z0=50.0)
rf.ABC(*air.faces.outer, order=1)

rf.show(g)


# %% Mesh
g.mesh()
rf.show(g)


# %% Solve across the frequency band
prob = rf.Problem(g)
result = prob.sweep(FREQS_HZ)
rf.show(prob)
rf.show(result)


# %% Extract L(f) from S → Z (series-L extraction with shunt de-embedding)
# Lumped-port plates over the local ground patch contribute a sizeable shunt
# capacitance at each port — Z11 ≈ Z21 ≈ Z_shunt dominates. The series
# inductance only shows up in their DIFFERENCE:
#     Z11 - Z21 ≈ Z_series = jωL_spiral
# Trying to extract L from Y21 alone is the classic trap — Im(Y21) is the
# tiny remainder of two nearly-equal shunt admittances and blows up the
# divided result.
I = np.eye(2)
print(f"Spiral: Dout={DOUT_UM:.0f}um Din={din_um:.0f}um N={N_TURNS} turns "
      f"w={WIDTH_UM:.0f}um s={SPACING_UM:.0f}um")
print(f"DOFs: {prob.n_dofs}, tets: {prob.n_tets}")
print(f"L (Mohan analytic) = {L_MOHAN * 1e9:.3f} nH")
print(f"{'f [GHz]':>9} {'L [nH]':>9} {'|S21|':>7} {'ratio L/Mohan':>14}")
for i, f in enumerate(FREQS_HZ):
    S = result.sparams[i]
    Z = math.sqrt(50.0) * (I + S) @ np.linalg.inv(I - S) * math.sqrt(50.0)
    L = (Z[0, 0].imag - Z[1, 0].imag) / (2 * math.pi * f)
    print(f"{f * 1e-9:>9.1f} {L * 1e9:>9.3f} {abs(S[1, 0]):>7.3f} {L / L_MOHAN:>14.2f}")
