[mesh]
file = "tools/spiral.msh"

[frequency]
values = [1000000000.0]

[[materials]]
volume_tag = 10
er = 11.7
ur = 1.0
tand = 0.0
conductivity = 1.000000e+01

[[materials]]
volume_tag = 11
er = 1.0
ur = 1.0
tand = 0.0
conductivity = 8.333333e+07

[[materials]]
volume_tag = 12
er = 1.0
ur = 1.0
tand = 0.0
conductivity = 6.666667e+07

[[materials]]
volume_tag = 13
er = 4.0
ur = 1.0
tand = 0.0
conductivity = 0.000000e+00

[[ports]]
type = "lumped"
tag = 14
z0 = 50
direction = [0, 0, 1]

[[ports]]
type = "lumped"
tag = 15
z0 = 50
direction = [0, 0, 1]

[pec]
tags = [1]

[solver]
prefer = "auto"

[output]
touchstone = "tools/spiral.s2p"
z0 = 50
vtk = "tools/spiral_fields.vtk"
